# Generated by Django 3.1.3 on 2020-11-26 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20201124_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.date(2020, 11, 26)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2020, 11, 26)),
        ),
    ]
