# Generated by Django 3.1.3 on 2021-01-03 03:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_auto_20201126_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.date(2021, 1, 2)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('ontheway', 'On The Way'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2021, 1, 2)),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
